### ISSUE TITLE
Mismatch in the env

### ISSUE THREAD

**Issue by harshakokel** [nathangrinsztajn/Box-World#3]
Hello, 

In the box-world environment provided by Deepmind in Pycolab ([here](https://github.com/deepmind/pycolab/tree/master/pycolab/examples/research/box_world)) key is collected on visiting the key location. From the GIFs, it seems in this environment the key is available as soon as the lock location is reached. 

Are you planning to match the behavior with the Pycolab environment?

**Comment by nathangrinsztajn** [comment]
Hello, 

It's a very good point. I put some thoughts about it at the beginning of the implementation and figured out collecting keys after immediately after removing their locks would remove some complexity overhead which isn't linked to relational reasoning.

Though I agree it could be left as a choice for the user, as a parameter of the environment. I'll do it asap !

**Comment by harshakokel** [comment]
Thank you. You are right the environment is complex enough as it is. This shouldn’t matter.

**Comment by nathangrinsztajn** [comment]
Done! Key collection patterns can be changed now with the collect_key parameter: if set to False, the keys aren't collected immediately anymore. Feel free to try, and hope it helps!

**Comment by harshakokel** [comment]
Thank you!
